Repository lidofinance/node-operators-setup, pull requests merged in 2023-03, with the labels that each got.

#3 [validators-ejector] feat: replace locator_address, add oracle_addresses_allowlist
  ansible/inventories/hosts.yml
  ansible/roles/lido_validator_ejector/templates/docker-compose.yml.j2
  variables
Labels: enhancement

#5 Testnet goerli
  README.md
  ansible/inventories/mainnet.yml
  ansible/inventories/testnet.yml
  base.sh
  variables
Labels: enhancement

#6 [keys-api] Upgrade image
  ansible/inventories/testnet.yml
Labels: keys-api

#2 Feat/prometheus alerts
  ansible/roles/alerts_box/files/prometheus_rules/cpu.rule.yml
  ansible/roles/alerts_box/files/prometheus_rules/cpu.test.yml
  ansible/roles/alerts_box/files/prometheus_rules/disk-latency.rule.yml
  ansible/roles/alerts_box/files/prometheus_rules/disk-latency.test.yml
  ansible/roles/alerts_box/files/prometheus_rules/disk-space.rule.yml
  ansible/roles/alerts_box/files/prometheus_rules/disk-space.test.yml
  ansible/roles/alerts_box/files/prometheus_rules/keys-api-outdated-keys.rule.yml
  ansible/roles/alerts_box/files/prometheus_rules/keys-api-outdated-keys.test.yml
  ansible/roles/alerts_box/files/prometheus_rules/keys-api-outdated-validators.rule.yml
  ansible/roles/alerts_box/files/prometheus_rules/keys-api-outdated-validators.test.yml
  ansible/roles/alerts_box/files/prometheus_rules/keys-api.rule.yml
  ansible/roles/alerts_box/files/prometheus_rules/keys-api.test.yml
  ansible/roles/alerts_box/files/prometheus_rules/memory.rule.yml
  ansible/roles/alerts_box/files/prometheus_rules/memory.test.yml
  ansible/roles/alerts_box/tasks/main.yml
  ansible/roles/alerts_box/templates/prometheus.yml.j2
  ansible/roles/service_geth_node/templates/docker-compose.yml.j2
Labels: enhancement

#10 feat: geth_node dashboard
  ansible/roles/alerts_box/files/dashboards/geth.json
Labels: geth, monitoring

#11 feat: update README
  README.md
Labels: documentation

#12 [Validator Ejector] 2 new allowed oracles in testnet
  ansible/inventories/testnet.yml
Labels: validators-ejector
